fixes broken stratigraphy legends in artefact/update #MC-360 Add Work Development 2h
 - disables global use of replace_terms filter for the whole artefact_update_page. (it was corrupting legend's html icons links when replacing some term in legend content.)

 - Selectively filter section content, complementary_information, image and stratigraphies legend texts and form field values for now

  caution: attempt to use replace_terms in more cases on the page (such as in help texts) leaded to exception in replace_terms filter code (their  html.py file)
  	   AttributeError: 'NoneType' object has no attribute 'getchildren'
     	   		   root_node = root_node.getchildren()[0]
           this was due to filter being applied on non html content (mostly blank string) and root_node then being None
	   this might also happen with this commit code depending on the content.

  	 todo: check then report or fix the django-terms issue