#MC-342 Add Work Development 1h Glossary Fixes error loading fonts via whitenoise because of terms middleware -  MICORR-2M sentry issue
  KeyError: 'content-type' execption in terms middleware while
  is_html = 'text/html' in response['Content-Type']

  production middleware configuration: insert WhiteNoise middleware after TermsMiddleware

  + updates sentry / raven client to latests version (6.2.1 -> 6.6.0)